### ISSUE TITLE
Fragment cache somtimes returns null despite cached data loading initially

### ISSUE THREAD

**Issue by RudiBoshoff** [DmitryTsepelev/graphql-ruby-fragment_cache#72]
Hi there, 

**ENV**:
We are currently using your gem on our Rails api which passes data through to an Apollo Angular app. We originally had a pure rails solution but got better performance results with your gem. 

**Issue**:
The problem is that sometimes the cache returns null. This doesn't happen locally but happens when we use the cache on Redis for staging and production. The cached data is returned most of the time but sometimes returns null. We have investigated as much as we could: we first thought it might be the front end but we have narrowed it down to the cache returning null. 

**How to reproduce**:
This only works some of the time 
1. load the site the first time to populate the cache (works)
2. hard refresh and reload the site (network results show that cache is working)
    ![image](https://user-images.githubusercontent.com/30492583/131299926-55ab5bf7-2625-4794-a595-49eeecee2570.png)
3. waiting a while (5 - 10 ish minutes) and loading the page again (returns null). The cache set to expire after 2 hours. Checking Redis shows that the key is still present when this failure occurs.
    ![image](https://user-images.githubusercontent.com/30492583/131299319-42382c18-c11c-4f60-9c80-da9bc966a499.png)

**Question**:
Do you have any ideas on what might be causing this or what we might be able to do? Thank you in advance.

**Comment by DmitryTsepelev** [comment]
Hi @RudiBoshoff!

That sounds really strange, because gem does reading in a [dead simple way](https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache/blob/1629c5f532b806d600bb8209252a9ff21b0369ba/lib/graphql/fragment_cache/fragment.rb#L51):

```ruby
FragmentCache.cache_store.read(cache_key).tap do |cached|
  return NIL_IN_CACHE if cached.nil? && FragmentCache.cache_store.exist?(cache_key)
end
```

In this case `FragmentCache.cache_store` is a Redis adapter, and if you see that key is still there, the value should be loaded without any issues. Since you know the key, could you please try to call `FragmentCache.cache_store.read(cache_key)` from the console and make sure value not `nil`?

Reading happens [here](https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache/blob/master/lib/graphql/fragment_cache/object_helpers.rb#L48), looks like it also does nothing more that a `nil`check.

**Comment by DmitryTsepelev** [comment]
Closing this for now, feel free to reopen 🙂

**Comment by gsdean** [comment]
FWIW: we're seeing similar behavior

**Comment by gsdean** [comment]
We've been doing some testing in production with the following

```
def value_from_cache
  return nil unless FragmentCache.cache_store.exist?(cache_key)

  FragmentCache.cache_store.read(cache_key).tap do |cached|
    return NIL_IN_CACHE if cached.nil? && FragmentCache.cache_store.exist?(cache_key)
  end
end
```

It seems to have addressed the race condition

**Comment by tsugitta** [comment]
@gsdean 
same here, can you explain how the workaround works? I understand the problem derives from fetching cache multiple times, but is it safe to fetch cache multiple times in that way?

**Comment by gsdean** [comment]
The workaround, isn't perfect. There is still a chance a race condition could cause a misread from the cache (specifically when an eviction occurs after the initial read, and then the cache is repopulated). Basically it reduces the risk of `value_from_cahe` incorrectly returning `nil` from **probable** to **less probable**. I'll let you decide if that is safe or not. 

For what it's worth we've tested both with and without this patch in a high load/concurrency production environment and without this patch we see numerous intermittent errors where nil is returned incorrectly. With the patch we have yet to have an error.

**Comment by DmitryTsepelev** [comment]
Sorry guys I don't know how but github does not sends me events from _some_ projects. I'll take a look tomorrow morning

**Comment by DmitryTsepelev** [comment]
If I understand correctly, the problem is that race condition makes cache to return `nil` even if it's not `nil` anymore. This is only possible when it was `nil` before cache was rewritten. I think this behavior is kinda acceptable, because user not gets _wrong_ data, it's just outdated, and the tradeoff of the cache is to have fast data vs. fresh data.

I guess we could add it to the docs and call it a day, what do you think?

**Comment by gsdean** [comment]
The cache returns the wrong value not an outdated value. I do not believe documentation alone is sufficient. In a moderately concurrent deployment, this is a serious issue.

**Comment by tsugitta** [comment]
> If I understand correctly, the problem is that race condition makes cache to return nil even if it's not nil anymore. 

in my situation, the problem seems that race condition makes cache to return nil even though it has never been nil before.

**Comment by DmitryTsepelev** [comment]
The only way to synchronize threads here is using some kind of lock: we could make it configurable and let users to opt–in. It will fix the issue completely but will slow down things a bit. WDYT?

**Comment by DmitryTsepelev** [comment]
Also, sounds like we could change the behavior to keep something different rather than `nil` in cache. In this case we will have no problems with differentiating scenarios "cache contains nil" and "cache does not have this key"

**Comment by tsugitta** [comment]
I'm not familiar with the cache API or instrumentation API, but it seems that the `read` method records whether or not there is a cache hit, so by using it, can't we call `read` only once without calling `exist?` ?

https://github.com/rails/rails/blob/d77c3fac9e8111a7f20cc5b4b2c686a7ad49d789/activesupport/lib/active_support/cache.rb#L419

**Comment by gsdean** [comment]
@tsugitta I agree, this is the most correct fix, but it seemed like a big change 🤷

**Comment by DmitryTsepelev** [comment]
Big change is not an issue, we can make a major release. The problem I'm trying to solve is that `read` returns `nil` in either when there's no such key at all (so we need to run the resolver method) and when there is a key with nil (so we want to return nil without running the resultion again). We also could add an option to force re–resolution when there's nil for any reason (e.g., `resolve_when_nil: true`).

Do you want to create the PR for the workaround?

**Comment by tsugitta** [comment]
> The problem I'm trying to solve is that read returns nil in either when there's no such key at all (so we need to run the resolver method) and when there is a key with nil (so we want to return nil without running the resultion again).

Yes, I'm also trying to solve the same problem. As I commented above, `read` seems to notify us with Instrumentation whether there is a cache hit or not, so by looking at it, we can determine whether the cache doesn't exist or the cache exists and the value is nil.
In addition, for the case where `nil` is regarded as a valid cache value, there seems to be an advantage that the two requests for `read` and `exist?` can be reduced to one.

Aside from that, the workaround seems great. I think it would be nice if I could submit a PR, but I haven't figured out the structure of the library yet, so I don't know where to start now and it may take some time. So at least I don't think I am the right person.

**Comment by tsugitta** [comment]
I had overlooked that the version I was using was outdated. After upgrading this library from `1.9.1` to `1.18.1` (and Rails from `6.1.4.4` to `7.0.4`), this problem, which used to happen dozens of times a day in our application that access cache frequently, never happened again.

**Comment by DmitryTsepelev** [comment]
Interesting 🤔I didn't remember we addressed it here in the gem, maybe something in Rails had changed for better

**Comment by gsdean** [comment]
As far as I can tell this is still an issue. Any thoughts on the PR? It would be really great to either merge that or leave this open until it’s resolved.
